server:
  port: ${PORT:3333}
  contextPath:   /auth

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKASERVER_URI:http://localhost:8761/eureka}
